name: Check fmt and clippy
disabled on:
  push:
    branches: [ "main", "actions/check" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_check:
    name: Check fmt and clippy

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build frontend
        run: |
          cd frontend
          npm install --silent
          npm run lint
          npm run check
          npm run prettier-check
          npm run build

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check fmt and clippy
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --no-default-features -- -D warnings
          cargo clippy --all-targets --no-default-features --features=dashboard -- -D warnings
          cargo clippy --all-targets --no-default-features --features=proxy -- -D warnings
          cargo clippy --all-targets --no-default-features --features=proxy,dashboard -- -D warnings
